- name: Copy tendermint binary to remote server
  copy:
    src: /usr/local/bin/tendermint
    dest: /usr/local/bin/tendermint
    owner: root # Optionally set the owner of the file
    group: root # Optionally set the group of the file
    mode: '0755' # Optionally set the mode. Use string to ensure leading zeros are not lost.

- name: Configure tendermint user
  shell: |
    sudo -i -u {{ tendermint_user }} bash << EOF

    if [[ \$PATH != \$HOME/go/bin* ]]; then
        echo 'export PATH="\$HOME/go/bin:\$PATH"' >> ~/.profile
    fi

    if [[ \$GOPATH != \$HOME/go ]]; then
        echo 'export GOPATH="\$HOME/go"' >> ~/.profile
    fi

    source ~/.profile
    EOF

# - name: Initialize tendermint
#   shell: |
#     sudo -i -u {{ tendermint_user }}  bash << EOF
#     tendermint init
#     EOF
#   become: yes

- name: Initialize tendermint
  shell: tendermint init
  # become: yes
  # become_user: "{{ tendermint_user }}"

- name: Place systemd unit file
  template:
    src: service.j2
    dest: /lib/systemd/system/tendermint.service
    owner: root
    group: root
    force: true
  become: yes
