---

- name: Connect nodes
  include_tasks: network.yml
  when: tendermint_connect_nodes

- name: Enable services
  shell: |
    systemctl daemon-reload
    systemctl enable tendermint
  become: yes

- name: Restart services
  shell: |
    systemctl restart tendermint
  become: yes

- name: Enable nginx
  shell: |
    systemctl enable nginx
    systemctl restart nginx
  become: yes
  when: nginx_enable
