---
- name: Users setup
  shell: |
    addgroup {{ bigchaindb_group }} \
        || echo {{ bigchaindb_group }} already exists
    adduser {{ bigchaindb_user }} \
        --ingroup {{ bigchaindb_group }} \
        --gecos '' \
        --disabled-password \
        || echo {{ bigchaindb_user }} already exists
    adduser {{ tendermint_user }} \
        --ingroup {{ bigchaindb_group }} \
        --gecos '' \
        --disabled-password \
        || echo {{ bigchaindb_user }} already exists
  become: yes
# TODO disable login

# - name: Install build requirements
#   apt:
#     name: "{{ packages }}"
#   vars:
#     packages:
#       # - make
#       # - build-essential
#       # - jq
#   become: yes
